### PR TITLE
upd to 2023.01.10

### PR DESCRIPTION
**Pull request by ekomarova**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ekomarova** [comment]
@conda-forge-admin, please rerender

**Comment by ekomarova** [comment]
Hi! Can you please help me to fix the license problem? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=692984&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=90

**Comment by ocefpaf** [comment]
> Hi! Can you please help me to fix the license problem?

It looks like the license file is not in the source you added.

```
ValueError: License file given in about/license_file (/home/conda/recipe_root/LICENSE.txt) does not exist in source root dir or in recipe root dir (with meta.yaml)
##[error]Bash exited with code '1'.
```

BTW, this package **is** supposed to be the PyPI curated one. Maybe changing the source to another one, even if that is more up-to-date, is not a good idea.

**Comment by jakirkham** [comment]
Maybe let's ask for an update ( https://github.com/certifi/python-certifi/issues/223 )

**Comment by jakirkham** [comment]
They just made a new release and this has been updated ( https://github.com/conda-forge/ca-certificates-feedstock/pull/60 ). Should we close?

**Comment by ekomarova** [comment]
I can say that this PR is no longer needed since a newer version has been merged

**Pull request closed without merging**
