### PR TITLE
Build from certifi's source

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/ca-certificates-feedstock/pull/8
Fixes https://github.com/conda-forge/ca-certificates-feedstock/issues/14

Proposing we switch to building this package directly from certifi's source. That should simplify the build and update process. Also allows us to package the license file.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thoughts on this @conda-forge/core? Seems this helps a few issues that have come up at this feedstock. Doesn't result in any changes to the package built other than inclusion of the license file.

**Comment by jjhelmus** [comment]
Another option would be to pull a `cacert.pem` file directly from another source such as https://curl.haxx.se/ca/cacert.pem.  Does exacting this file from the certifi source provide some additional security?

**Comment by jjhelmus** [comment]
https://curl.haxx.se/docs/caextract.html Has dated versions of the file as well.

**Comment by jakirkham** [comment]
We can discuss that, but I feel like that is a separate issue. The only things I'm trying to address in this PR is issues raised by others regarding the complexity of building this simple package and ensuring a license is included. The actual certificates used are exactly the same here as before. If we want to change them, that seems like something totally different.

**Comment by jjhelmus** [comment]
Thanks for additional explanation @jakirkham, I'm in favor of this change.

**Comment by jakirkham** [comment]
Thanks @jjhelmus. If you are interested in changing the source of the certificates still, would be happy to discuss that with you in a new issue.

**Comment by jjhelmus** [comment]
After reflection, I'm not that worried about the source.  Certifi uses PyPI which we know a lot about so I'm fine keeping it there.  Just wanted to offer an alternative.

**Pull request merged**
